name = "night-owl-presence"
main = "worker.js"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "PRESENCE_DO", class_name = "PresenceDurableObject" }
]

[[migrations]]
tag = "v1"
new_classes = ["PresenceDurableObject"]

[site]
bucket = "./"
